name: Pull Request Build

on:
  pull_request:
    types: [ labeled ]

jobs:
  pr-build:
    if: ${{ github.event.label.name == 'run-build' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
