name: Reviewpad

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
      - edited
  workflow_run:
    workflows: ["Pull Request Build"]
    types:
      - completed

jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@canary
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}
